### ISSUE TITLE
POST MODEL

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/only-cute-api#11]
Add Post Model

### Tasks
 - [x] Create post app
 - [x] Create post model
 - [x] Create post serializer
