### ISSUE TITLE
POST IMAGE VALIDATION

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/only-cute-api#18]
Add Post Image Validation

### Tasks
 - [x] Add image size validation
 - [x] Add image width validation
 - [x] Add image height validation
