### ISSUE TITLE
SET UP API ENVIRONMENT

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/only-cute-api#2]
Initial setup up of the API environment

### Tasks
 - [x] Create a repository
 - [x] Create gitpod workspace
 - [x] Install Django and Cloudinary  and Pillow
 - [x] Set up Cloudinary
 - [x] Install Django Rest Framework
