### ISSUE TITLE
COMMENT MODEL

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/only-cute-api#20]
Add Comment Model

### Tasks
 - [x] Create comments app
 - [x] Create comment model
 - [x] Create comment serializer
