### ISSUE TITLE
PROFILE PERMISSIONS

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/only-cute-api#3]
Add is owner permission to non safe methods of the profile

### Tasks
 - [x] Create permission to check if the user is the owner
 - [x] Connect permission to profile detail view
 - [x] Pass the request data from views.py as a context value for each method
 - [x] Add the permission details to each profile
