### ISSUE TITLE
PROFILE MODEL

### ISSUE THREAD

**Issue by AlmaBroman** [AlmaBroman/only-cute-api#7]
Create profile model

### Tasks
 - [x] Create profiles app
 - [x] Create profile model
 - [x] Create profile serializer
